;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim
        indent-for-tab-command
        keyboard-quit
        kill-region
        kill-sexp
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        universal-argument-minus
        whole-line-or-region-kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        god-local-mode
        ))
